version: '3.8'
services:
  n8n:
    image: n8nio/n8n
    container_name: sentra-n8n
    restart: always
    ports:
      - '5678:5678'
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=Africa/Kigali
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
    extra_hosts:
      - 'host.docker.internal:host-gateway'
volumes:
  n8n_data:
